### PR TITLE
Extend pulsing red dot

### PR DESCRIPTION
**Pull request by adgad**
/cc @wheresrhys @phamann

### CODE REVIEW

**Comment by commuterjoy** [comment]
How are you measuring the effectiveness of it?

**Comment by adgad** [comment]
At the moment we're measuring clicks on myFT with or without a notification (but that's not specifically this flag, which is just related to the animation). It's perhaps something we could AB test? - hypothesis being that the animation generates more visits to myFT (but not sure yet that that is a journey we will want to promote once we have emails/push etc in place...)

**Comment by adgad** [comment]
Or let it expire and see it have no difference whatsoever on clicks.

**Comment by commuterjoy** [comment]
> It's perhaps something we could AB test?

Yep, probably need more users before we test subtle things like that.

**Pull request merged**
