### PR TITLE
remove cors

### PR DESCRIPTION
**Pull request by wheresrhys**
won't be needed after this https://github.com/Financial-Times/next-feature-flags-client/pull/33

@matthew-andrews @commuterjoy

### CODE REVIEW

**Comment by matthew-andrews** [comment]
umm

how about for running next-header locally?

**Comment by matthew-andrews** [comment]
:-1:

**Comment by wheresrhys** [comment]
see https://github.com/Financial-Times/next-js-setup/pull/2/files.

Next-header's demo templates haven't been updated for ages anyway. Standalone demos would be good, but the current implementation is less good than just using `bower link` so I don't mind breaking it for now

Also, next-header could fire up the router too could it not and then would be same domain?

**Comment by wheresrhys** [comment]
but this PR isn't urgent, it just clouds the waters a little with trying to get a cors implementation that works for user-prefs used everywhere

**Comment by matthew-andrews** [comment]
> Next-header's demo templates haven't been updated for ages anyway.

!!!  fix them !!!

> Standalone demos would be good, but the current implementation is less good than just using bower link so I don't mind breaking it for now

No!  we should be able to develop repositories standalone.  last i worked on that that was the case.  if not anymore, it's a regression.

> Also, next-header could fire up the router too could it not and then would be same domain?

no, this is a component, not an app.

**Comment by wheresrhys** [comment]
parked for now until flags no longer in components

**Pull request closed without merging**
