### PR TITLE
Just json

### PR DESCRIPTION
**Pull request by matthew-andrews**
This is all the flags api does really.  Using curl isn't really any easier than making a pull request and this way we get history, rollback, backups with restores for free.

### CODE REVIEW

**Comment by matthew-andrews** [comment]
This also fixes #18 #14 and fixes these URLs: http://ft-next-api-feature-flags.herokuapp.com/production/ads that just don't work at the moment.

**Comment by commuterjoy** [comment]
Do you think this is a long term solution or just gets rid of redis asap?

**Comment by matthew-andrews** [comment]
it fixes an awful lot of stuff…  @adgad pointed out this also gives us proper security (from a simple alphanumerical password that the docs encouraged us to send over http to changes made over SSL backed by 2 factor authentication).  as long as we can continue measuring deploys in seconds i think it's ok for long term imho, and if in the future we decide we need a more flexible api, all we need to do is put a database on it.  although since that database is unlikely to be redis it's unlikely we'd be able to reuse the code.

**Comment by commuterjoy** [comment]
@matthew-andrews yes, I think that's fair.

**Comment by matthew-andrews** [comment]
@richard-still-ft makes a good point also.  This does mean we lose the ability to switch off features instantly.  So I think that rules this out as a long-long term solution but for now, tentatively, this is still gives us more than we lose?

**Comment by commuterjoy** [comment]
instantly thought was alway 'up to the polling interval', which was 60 seconds.

I think it also makes it harder for people outside the team to control things - feasibly a product manager, duty ops etc. might decide to turn something off.

**Comment by commuterjoy** [comment]
If you want to keep it perhaps http://aws.amazon.com/elasticache/ is a better / more stable hosted redis solution

**Pull request merged**
